//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bdl_Grupo2_ProyectoFinal_A
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recordatorios
    {
        public int Rcdt_Id { get; set; }
        public string Rcdt_Descripcion { get; set; }
        public Nullable<int> Tkt_Id { get; set; }
        public Nullable<System.DateTime> Rcdt_Fecha { get; set; }
    
        public virtual Tickets Tickets { get; set; }
    }
}
