//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bdl_Grupo2_ProyectoFinal_A
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tickets()
        {
            this.Recordatorios = new HashSet<Recordatorios>();
        }
    
        public int Tkt_Id { get; set; }
        public int aceptado { get; set; }
        public string Tkt_Codigo { get; set; }
        public Nullable<int> Tec_Id { get; set; }
        public Nullable<int> TktPrd_Id { get; set; }
        public Nullable<int> PrbTc_Id { get; set; }
        public Nullable<int> EstdTick_Id { get; set; }
        public Nullable<int> Usr_Id { get; set; }
        public string Tkt_Descripcion { get; set; }
        public Nullable<int> Eqs_Id { get; set; }
        public System.DateTime Tkt_Fecha_Hora { get; set; }
    
        public virtual Equipos Equipos { get; set; }
        public virtual Estado_Ticket Estado_Ticket { get; set; }
        public virtual Problemas_Tecnicos Problemas_Tecnicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recordatorios> Recordatorios { get; set; }
        public virtual Tecnicos Tecnicos { get; set; }
        public virtual Ticket_Prioridad Ticket_Prioridad { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
