//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bdl_Grupo2_ProyectoFinal_A
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsrTecnicos
    {
        public int UsrTecnico_Id { get; set; }
        public int aceptado { get; set; }
        public string UsrTecnico_Correo { get; set; }
        public string UsrTecnico_Password { get; set; }
        public Nullable<int> Tec_Id { get; set; }
    
        public virtual Tecnicos Tecnicos { get; set; }
    }
}
